version: "3.7"

services:

  web:
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/marco27.net
      - ./nginx/site.conf:/etc/nginx/conf.d/marco27.net.conf
    depends_on:
      - php
      - mariadb

  php:
    image: php:7.4-fpm
    volumes:
      - ./www:/var/www/marco27.net
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    restart: always
    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./sql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data:
